#Dimensões Tipo 1

CREATE TABLE DIM_UTENTE
(SK_UTENTE INTEGER NOT NULL,
UTENTE_ID VARCHAR(20),
NOME VARCHAR(200),
PRIMARY KEY(SK_UTENTE)
);
CREATE INDEX NUTEN_IDX ON DIM_UTENTE (UTENTE_ID);

 DROP TABLE dim_utente

#Dimensões Tipo 2

CREATE TABLE DIM_SERVICO
(SK_SERVICO INTEGER NOT NULL,
 SERVICO_ID VARCHAR(4),
 NOME_SERVICO VARCHAR(200),
 DTC_INICIO DATETIME,
 DTC_FIM DATETIME,
 PRIMARY KEY(SK_SERVICO)
 );
 CREATE INDEX NSER_IDX ON DIM_SERVICO (SERVICO_ID);
 
 DROP TABLE dim_servico
 SELECT * FROM projeto.dim_servico;


CREATE TABLE DIM_PRODUTOFARMACEUTICO
(SK_PRODUTOFARMACEUTICO INTEGER NOT NULL,
 PRODUTOFARMACEUTICO_ID INTEGER,
 NOME_PRODUTO VARCHAR(200),
 TIPO_UNIDADE VARCHAR(100),
 DTC_INICIO DATETIME,
 DTC_FIM DATETIME,
 PRIMARY KEY(SK_PRODUTOFARMACEUTICO)
 );
 CREATE INDEX NPROD_IDX ON DIM_PRODUTOFARMACEUTICO (PRODUTOFARMACEUTICO_ID);
 
 
DROP TABLE dim_produtofarmaceutico
SELECT * FROM projeto.dim_produtofarmaceutico;

CREATE TABLE DIM_ENTIDADERESPONSAVEL
(SK_ENTIDADERESPONSAVEL INTEGER NOT NULL,
 ENTIDADE_RESPONSAVEL_ID INTEGER,
 ENTIDADE_RESPONSAVEL VARCHAR(200),
 DTC_INICIO DATETIME,
 DTC_FIM DATETIME,
 PRIMARY KEY(SK_ENTIDADERESPONSAVEL)
 );
  CREATE INDEX NENT_IDX ON DIM_ENTIDADERESPONSAVEL (ENTIDADE_RESPONSAVEL_ID)
  
  DROP TABLE dim_entidaderesponsavel
  SELECT * FROM projeto.dim_entidaderesponsavel;
  

#FAZER UPDATES
UPDATE stg_produtofarmaceutico stg_p
SET stg_p.Nome_Produto = "Paracetamol 10 mg/ml Sol inj Fr 100 ml IV"
WHERE stg_p.Nome_Produto = "BUR";