CREATE TABLE DIM_DATA
   (SK_DATA INTEGER NOT NULL, 
	DES_DATA_DIA VARCHAR(25), 
	DTC_DATA DATE, 
	NUM_ANO INTEGER, 
	NUM_MES INTEGER, 
	NUM_DIA INTEGER, 
	NUM_QUADRIMESTRE INTEGER, 
	NUM_TRIMESTRE INTEGER, 
	DES_QUINZENA VARCHAR(12), 
	DES_QUADRIMESTRE VARCHAR(12), 
	NUM_BIMESTRE INTEGER, 
	DES_BIMESTRE VARCHAR(12), 
	DES_ANO_MES VARCHAR(8), 
	DES_DIA VARCHAR(7), 
	NUM_SEMESTRE INTEGER, 
	DES_MES_ANO_NUMERICO VARCHAR(7), 
	DES_TRIMESTRE VARCHAR(12), 
	IND_FINAL_SEMANA CHAR(1), 
	DES_MES VARCHAR(15), 
	NUM_QUINZENA INTEGER, 
	DES_MES_ANO_COMPLETO VARCHAR(30), 
	DES_SEMESTRE VARCHAR(12), 
	NUM_NIVEL INTEGER, 
	DES_MES_ANO VARCHAR(8), 
	 CONSTRAINT DIM_DATA_DIM_KEY_PKT PRIMARY KEY (SK_DATA));
     
CREATE INDEX TEMPO_IDX ON DIM_DATA (DES_DATA_DIA);

 DROP TABLE dim_data
TRUNCATE dim_data